name: reup
description: reup app
publish_to: "none"

version: 1.0.0

dependencies:
  alice: 0.3.2
  auto_route: 7.4.0
  cached_network_image: 3.3.0
  # collection: 1.17.1
  cupertino_icons: 1.0.6
  dio: 4.0.6
  equatable: 2.0.5
  firebase_core: 2.15.0
  firebase_crashlytics: 3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 8.0.0
  flutter_svg: 2.0.7
  get_it: 7.6.4
  getwidget: 4.0.0
  google_fonts: 4.0.4
  infinite_carousel: 1.0.3
  internet_connection_checker: 1.0.0+1
  intl: 0.18.1
  json_annotation: 4.8.1
  logger: 1.3.0
  pinput: 3.0.1
  retrofit: 3.3.1
  shared_preferences: 2.1.0
  smooth_page_indicator: 1.1.0
  surf_logger: 1.1.0
  visibility_detector: 0.4.0+2

dev_dependencies:
  auto_route_generator: 7.1.1
  build_runner: 2.3.3
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.1
  flutter_test:
    sdk: flutter
  golden_toolkit: 0.15.0
  json_serializable: 6.6.1
  mocktail: 0.3.0
  retrofit_generator: 4.2.0
  spider: 4.2.1
  surf_lint_rules: 3.0.0

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: 3.10.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
