name: reup
description: reup app
publish_to: "none"

version: 1.0.0

dependencies:
  alice: 0.3.3
  auto_route: 7.8.4
  cupertino_icons: 1.0.6
  cached_network_image: 3.3.0
  dio: 5.3.3
  equatable: 2.0.5
  firebase_crashlytics: 3.3.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_secure_storage: 9.0.0
  flutter_svg: 2.0.7
  getwidget: 4.0.0
  get_it: 7.6.4
  google_fonts: ^6.1.0
  infinite_carousel: 1.0.3
  internet_connection_checker: ^1.0.0+1
  intl: 0.18.1
  json_annotation: 4.8.1
  pinput: 3.0.1
  visibility_detector: "^0.4.0+2"
  retrofit: 4.0.2
  shared_preferences: 2.2.1
  smooth_page_indicator: 1.1.0
  surf_logger: 1.1.0

dev_dependencies:
  auto_route_generator: 7.3.2
  build_runner: 2.4.6
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.3
  flutter_test:
    sdk: flutter
  golden_toolkit: 0.15.0
  json_serializable: 6.7.1
  mocktail: 1.0.1
  retrofit_generator: 8.0.0
  spider: 4.2.1
  surf_lint_rules: 3.0.0

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: 3.10.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
